name: Coverage

on:
  pull_request:
  push:
    branches: [master]

jobs:
  coverage:
    name: Hardhat
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --max_old_space_size=6400

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Collect coverage
        run: yarn test:coverage

      - name: Produce the coverage report
        uses: lidofinance/coverage-action@a94351baa279790f736655b1891178b1515594ea
        with:
          path: ./coverage/cobertura-coverage.xml
          publish: true
          # TODO: restore to 95% before release
          threshold: 80
          diff: true
          diff-branch: master
          diff-storage: _core_coverage_reports
          coverage-summary-title: "Hardhat Unit Tests Coverage Summary"
          togglable-report: true
