name: Integration Test For Upgrade Template

on: [push]

jobs:
  test_hardhat_integration_fork_template:
    name: Hardhat / Upgrade Template
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      SKIP_GAS_REPORT: true
      SKIP_CONTRACT_SIZE: true
      SKIP_INTERFACES_CHECK: true

    steps:
      - uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/workflows/setup

      - name: Prepare network state file
        run: cp deployed-mainnet.json deployed-mainnet-upgrade.json

      - name: Run Upgrade Template Integration Tests
        run: yarn test:integration:upgrade-template
        env:
          RPC_URL: "${{ secrets.ETH_RPC_URL }}"
          UPGRADE_PARAMETERS_FILE: scripts/upgrade/upgrade-params-mainnet.toml
